# print("Anuj\nDhumane")
# print("\n")
# print("Anuj\'Dhumane")
# print("\n")
# print("Anuj\tDhumane")
# print("\n")
# print("Anuj \bDhumane")
# print("Anuj \fDhumane")
# print("Anuj \bDhumane")
print("Anuj \rDhumane")
